name: Daily Check

on:
  schedule:
    - cron: '50 23 * * *'  # Run daily at 23:50 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create cookies file
      run: |
        echo "${{ secrets.AICODEMIRROR_COOKIES }}" > aicodemirror_cookies.txt
        
    - name: Run check script
      run: python aicode.py check