name: Daily Refresh

on:
  schedule:
    - cron: '0 12 * * *'  # Run every day at 12:00 UTC, 20:00 in China
  workflow_dispatch:  # Allow manual triggering

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create cookies file
      run: |
        echo "${{ secrets.AICODEMIRROR_COOKIES }}" > aicodemirror_cookies.txt

    - name: Run refresh script
      run: python aicode.py refresh
